ALTER TABLE card
  ADD COLUMN name VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE studentcard
  ADD COLUMN name VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE studentcard
  ADD COLUMN allowedsubjectsmask INTEGER NOT NULL DEFAULT 63;