const {combineReducers} = require('redux'),
    Utils = require('../Utils'),
    Profile = require('./ProfileReducer'),
    GlobalReducer = require('./GlobalReducer'),
    common = require('./CommonReducer'),
    Lessons = require('./LessonsReducer'),
    Students = require('./StudentsReducer'),
    Student = require('./StudentReducer'),
    StudentCard = require('./StudentCardReducer'),
    StudentCall = require('./StudentCallReducer'),
    PromotionSources = require('./PromotionSourcesReducer'),
    PromotionDetails = require('./PromotionDetailsReducer'),
    Cards = require('./CardsReducer'),
    Card = require('./CardReducer'),
    StudentCalls = require('./StudentCallsReducer'),
    Teachers = require('./TeachersReducer'),
    Teacher = require('./TeacherReducer'),
    LessonTemplate = require('./LessonTemplateReducer'),
    LessonTemplates = require('./LessonTemplatesReducer'),
    Payments = require('./PaymentsReducer'),
    Payment = require('./PaymentReducer'),
    Cities = require('./CitiesReducer'),
    City = require('./CityReducer'),
    Schools = require('./SchoolsReducer'),
    School = require('./SchoolReducer'),
    Accounts = require('./AccountsReducer'),
    Account = require('./AccountReducer'),
    Categories = require('./CategoriesReducer'),
    Category = require('./CategoryReducer'),
    Users = require('./UsersReducer'),
    User = require('./UserReducer'),
    Roles = require('./RolesReducer'),
    Role = require('./RoleReducer'),
    Homeworks = require('./HomeworksReducer'),
    Homework = require('./HomeworkReducer'),
    RegisterForm = require('./RegisterFormReducer'),
    RelativeChildren = require('./RelativeChildrenReducer'),
    Preferences = require('./PreferencesReducer'),
    Siblings = require('./SiblingsReducer');

const reducers = Utils.chainReducers(GlobalReducer, combineReducers({
    common,
    pages: combineReducers({
        Lessons, Profile,
        Students, Student, StudentCard, StudentCall, StudentCalls,
        PromotionSources, PromotionDetails,
        Cards, Card,
        Teachers, Teacher,
        LessonTemplates, LessonTemplate,
        Payments, Payment,
        Cities, City,
        Schools, School,
        Accounts, Account,
        Categories, Category,
        Users, User,
        Roles, Role,
        Homeworks, Homework,
        RegisterForm, RelativeChildren,
        Preferences,
        Siblings
    })
}));

module.exports = reducers;
